// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    uint64_t capacity;
    uint64_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H
#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t, int8_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
typedef void (*UniffiForeignFutureFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE
typedef struct UniffiForeignFuture {
    uint64_t handle;
    UniffiForeignFutureFree _Nonnull free;
} UniffiForeignFuture;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
typedef struct UniffiForeignFutureStructU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t, UniffiForeignFutureStructU8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
typedef struct UniffiForeignFutureStructI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t, UniffiForeignFutureStructI8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
typedef struct UniffiForeignFutureStructU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t, UniffiForeignFutureStructU16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
typedef struct UniffiForeignFutureStructI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t, UniffiForeignFutureStructI16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
typedef struct UniffiForeignFutureStructU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t, UniffiForeignFutureStructU32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
typedef struct UniffiForeignFutureStructI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t, UniffiForeignFutureStructI32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
typedef struct UniffiForeignFutureStructU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t, UniffiForeignFutureStructU64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
typedef struct UniffiForeignFutureStructI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t, UniffiForeignFutureStructI64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
typedef struct UniffiForeignFutureStructF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t, UniffiForeignFutureStructF32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
typedef struct UniffiForeignFutureStructF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t, UniffiForeignFutureStructF64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
typedef struct UniffiForeignFutureStructPointer {
    void*_Nonnull returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructPointer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
typedef void (*UniffiForeignFutureCompletePointer)(uint64_t, UniffiForeignFutureStructPointer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
typedef struct UniffiForeignFutureStructRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t, UniffiForeignFutureStructRustBuffer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
typedef struct UniffiForeignFutureStructVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureStructVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t, UniffiForeignFutureStructVoid
    );

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_FN_CLONE_CANCELTOKEN
#define UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_FN_CLONE_CANCELTOKEN
void*_Nonnull uniffi_smix_ffi_fn_clone_canceltoken(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_FN_FREE_CANCELTOKEN
#define UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_FN_FREE_CANCELTOKEN
void uniffi_smix_ffi_fn_free_canceltoken(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_FN_METHOD_CANCELTOKEN_CANCEL
#define UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_FN_METHOD_CANCELTOKEN_CANCEL
void uniffi_smix_ffi_fn_method_canceltoken_cancel(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_FN_METHOD_CANCELTOKEN_IS_CANCELLED
#define UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_FN_METHOD_CANCELTOKEN_IS_CANCELLED
int8_t uniffi_smix_ffi_fn_method_canceltoken_is_cancelled(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_FN_CLONE_SMIXDRIVER
#define UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_FN_CLONE_SMIXDRIVER
void*_Nonnull uniffi_smix_ffi_fn_clone_smixdriver(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_FN_FREE_SMIXDRIVER
#define UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_FN_FREE_SMIXDRIVER
void uniffi_smix_ffi_fn_free_smixdriver(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_FN_CONSTRUCTOR_SMIXDRIVER_NEW
#define UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_FN_CONSTRUCTOR_SMIXDRIVER_NEW
void*_Nonnull uniffi_smix_ffi_fn_constructor_smixdriver_new(uint16_t port, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_FN_METHOD_SMIXDRIVER_CANCEL_TOKEN
#define UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_FN_METHOD_SMIXDRIVER_CANCEL_TOKEN
void*_Nonnull uniffi_smix_ffi_fn_method_smixdriver_cancel_token(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_FN_METHOD_SMIXDRIVER_LIST_SESSIONS
#define UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_FN_METHOD_SMIXDRIVER_LIST_SESSIONS
uint64_t uniffi_smix_ffi_fn_method_smixdriver_list_sessions(void*_Nonnull ptr, RustBuffer cancel
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_FN_METHOD_SMIXDRIVER_OPEN_SESSION
#define UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_FN_METHOD_SMIXDRIVER_OPEN_SESSION
uint64_t uniffi_smix_ffi_fn_method_smixdriver_open_session(void*_Nonnull ptr, RustBuffer bundle_id, RustBuffer cancel
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_FN_METHOD_SMIXDRIVER_TREE
#define UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_FN_METHOD_SMIXDRIVER_TREE
uint64_t uniffi_smix_ffi_fn_method_smixdriver_tree(void*_Nonnull ptr, RustBuffer cancel
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_FN_CLONE_SMIXSESSION
#define UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_FN_CLONE_SMIXSESSION
void*_Nonnull uniffi_smix_ffi_fn_clone_smixsession(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_FN_FREE_SMIXSESSION
#define UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_FN_FREE_SMIXSESSION
void uniffi_smix_ffi_fn_free_smixsession(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_FN_METHOD_SMIXSESSION_CLOSE
#define UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_FN_METHOD_SMIXSESSION_CLOSE
uint64_t uniffi_smix_ffi_fn_method_smixsession_close(void*_Nonnull ptr, RustBuffer cancel
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_FN_METHOD_SMIXSESSION_ID
#define UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_FN_METHOD_SMIXSESSION_ID
RustBuffer uniffi_smix_ffi_fn_method_smixsession_id(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_FN_METHOD_SMIXSESSION_INPUT_TEXT
#define UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_FN_METHOD_SMIXSESSION_INPUT_TEXT
uint64_t uniffi_smix_ffi_fn_method_smixsession_input_text(void*_Nonnull ptr, RustBuffer text, RustBuffer cancel
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_FN_METHOD_SMIXSESSION_LAUNCH_APP
#define UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_FN_METHOD_SMIXSESSION_LAUNCH_APP
uint64_t uniffi_smix_ffi_fn_method_smixsession_launch_app(void*_Nonnull ptr, RustBuffer cancel
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_FN_METHOD_SMIXSESSION_PRESS_KEY
#define UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_FN_METHOD_SMIXSESSION_PRESS_KEY
uint64_t uniffi_smix_ffi_fn_method_smixsession_press_key(void*_Nonnull ptr, RustBuffer key, RustBuffer cancel
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_FN_METHOD_SMIXSESSION_RELAUNCH_APP
#define UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_FN_METHOD_SMIXSESSION_RELAUNCH_APP
uint64_t uniffi_smix_ffi_fn_method_smixsession_relaunch_app(void*_Nonnull ptr, RustBuffer cancel
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_FN_METHOD_SMIXSESSION_RENEW_ACTIVATION
#define UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_FN_METHOD_SMIXSESSION_RENEW_ACTIVATION
uint64_t uniffi_smix_ffi_fn_method_smixsession_renew_activation(void*_Nonnull ptr, RustBuffer cancel
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_FN_METHOD_SMIXSESSION_SWIPE_ONCE
#define UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_FN_METHOD_SMIXSESSION_SWIPE_ONCE
uint64_t uniffi_smix_ffi_fn_method_smixsession_swipe_once(void*_Nonnull ptr, RustBuffer direction, RustBuffer cancel
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_FN_METHOD_SMIXSESSION_SYSTEM_POPUPS
#define UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_FN_METHOD_SMIXSESSION_SYSTEM_POPUPS
uint64_t uniffi_smix_ffi_fn_method_smixsession_system_popups(void*_Nonnull ptr, RustBuffer cancel
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_FN_METHOD_SMIXSESSION_TAP_AT_NORM_COORD
#define UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_FN_METHOD_SMIXSESSION_TAP_AT_NORM_COORD
uint64_t uniffi_smix_ffi_fn_method_smixsession_tap_at_norm_coord(void*_Nonnull ptr, double nx, double ny, RustBuffer cancel
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_FN_METHOD_SMIXSESSION_TAP_BY_ID
#define UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_FN_METHOD_SMIXSESSION_TAP_BY_ID
uint64_t uniffi_smix_ffi_fn_method_smixsession_tap_by_id(void*_Nonnull ptr, RustBuffer id, RustBuffer cancel
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_FN_METHOD_SMIXSESSION_TERMINATE_APP
#define UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_FN_METHOD_SMIXSESSION_TERMINATE_APP
uint64_t uniffi_smix_ffi_fn_method_smixsession_terminate_app(void*_Nonnull ptr, RustBuffer cancel
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_FN_FUNC_RESOLVE_SELECTOR
#define UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_FN_FUNC_RESOLVE_SELECTOR
RustBuffer uniffi_smix_ffi_fn_func_resolve_selector(RustBuffer tree_json, RustBuffer selector_json, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_FN_FUNC_RESOLVE_SELECTOR_COUNT
#define UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_FN_FUNC_RESOLVE_SELECTOR_COUNT
uint32_t uniffi_smix_ffi_fn_func_resolve_selector_count(RustBuffer tree_json, RustBuffer selector_json, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_FN_FUNC_RESOLVE_SELECTOR_LABELS
#define UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_FN_FUNC_RESOLVE_SELECTOR_LABELS
RustBuffer uniffi_smix_ffi_fn_func_resolve_selector_labels(RustBuffer tree_json, RustBuffer selector_json, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SMIX_FFI_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_SMIX_FFI_RUSTBUFFER_ALLOC
RustBuffer ffi_smix_ffi_rustbuffer_alloc(uint64_t size, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SMIX_FFI_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_SMIX_FFI_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_smix_ffi_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SMIX_FFI_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_SMIX_FFI_RUSTBUFFER_FREE
void ffi_smix_ffi_rustbuffer_free(RustBuffer buf, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SMIX_FFI_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_SMIX_FFI_RUSTBUFFER_RESERVE
RustBuffer ffi_smix_ffi_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_POLL_U8
void ffi_smix_ffi_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_CANCEL_U8
void ffi_smix_ffi_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_FREE_U8
void ffi_smix_ffi_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_smix_ffi_rust_future_complete_u8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_POLL_I8
void ffi_smix_ffi_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_CANCEL_I8
void ffi_smix_ffi_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_FREE_I8
void ffi_smix_ffi_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_COMPLETE_I8
int8_t ffi_smix_ffi_rust_future_complete_i8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_POLL_U16
void ffi_smix_ffi_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_CANCEL_U16
void ffi_smix_ffi_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_FREE_U16
void ffi_smix_ffi_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_smix_ffi_rust_future_complete_u16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_POLL_I16
void ffi_smix_ffi_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_CANCEL_I16
void ffi_smix_ffi_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_FREE_I16
void ffi_smix_ffi_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_COMPLETE_I16
int16_t ffi_smix_ffi_rust_future_complete_i16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_POLL_U32
void ffi_smix_ffi_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_CANCEL_U32
void ffi_smix_ffi_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_FREE_U32
void ffi_smix_ffi_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_smix_ffi_rust_future_complete_u32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_POLL_I32
void ffi_smix_ffi_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_CANCEL_I32
void ffi_smix_ffi_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_FREE_I32
void ffi_smix_ffi_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_COMPLETE_I32
int32_t ffi_smix_ffi_rust_future_complete_i32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_POLL_U64
void ffi_smix_ffi_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_CANCEL_U64
void ffi_smix_ffi_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_FREE_U64
void ffi_smix_ffi_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_smix_ffi_rust_future_complete_u64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_POLL_I64
void ffi_smix_ffi_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_CANCEL_I64
void ffi_smix_ffi_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_FREE_I64
void ffi_smix_ffi_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_COMPLETE_I64
int64_t ffi_smix_ffi_rust_future_complete_i64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_POLL_F32
void ffi_smix_ffi_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_CANCEL_F32
void ffi_smix_ffi_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_FREE_F32
void ffi_smix_ffi_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_COMPLETE_F32
float ffi_smix_ffi_rust_future_complete_f32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_POLL_F64
void ffi_smix_ffi_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_CANCEL_F64
void ffi_smix_ffi_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_FREE_F64
void ffi_smix_ffi_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_COMPLETE_F64
double ffi_smix_ffi_rust_future_complete_f64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_POLL_POINTER
#define UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_POLL_POINTER
void ffi_smix_ffi_rust_future_poll_pointer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_CANCEL_POINTER
#define UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_CANCEL_POINTER
void ffi_smix_ffi_rust_future_cancel_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_FREE_POINTER
#define UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_FREE_POINTER
void ffi_smix_ffi_rust_future_free_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_COMPLETE_POINTER
void*_Nonnull ffi_smix_ffi_rust_future_complete_pointer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_smix_ffi_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_smix_ffi_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_smix_ffi_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_smix_ffi_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_POLL_VOID
void ffi_smix_ffi_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_CANCEL_VOID
void ffi_smix_ffi_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_FREE_VOID
void ffi_smix_ffi_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_SMIX_FFI_RUST_FUTURE_COMPLETE_VOID
void ffi_smix_ffi_rust_future_complete_void(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_CHECKSUM_FUNC_RESOLVE_SELECTOR
#define UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_CHECKSUM_FUNC_RESOLVE_SELECTOR
uint16_t uniffi_smix_ffi_checksum_func_resolve_selector(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_CHECKSUM_FUNC_RESOLVE_SELECTOR_COUNT
#define UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_CHECKSUM_FUNC_RESOLVE_SELECTOR_COUNT
uint16_t uniffi_smix_ffi_checksum_func_resolve_selector_count(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_CHECKSUM_FUNC_RESOLVE_SELECTOR_LABELS
#define UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_CHECKSUM_FUNC_RESOLVE_SELECTOR_LABELS
uint16_t uniffi_smix_ffi_checksum_func_resolve_selector_labels(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_CHECKSUM_METHOD_CANCELTOKEN_CANCEL
#define UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_CHECKSUM_METHOD_CANCELTOKEN_CANCEL
uint16_t uniffi_smix_ffi_checksum_method_canceltoken_cancel(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_CHECKSUM_METHOD_CANCELTOKEN_IS_CANCELLED
#define UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_CHECKSUM_METHOD_CANCELTOKEN_IS_CANCELLED
uint16_t uniffi_smix_ffi_checksum_method_canceltoken_is_cancelled(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_CHECKSUM_METHOD_SMIXDRIVER_CANCEL_TOKEN
#define UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_CHECKSUM_METHOD_SMIXDRIVER_CANCEL_TOKEN
uint16_t uniffi_smix_ffi_checksum_method_smixdriver_cancel_token(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_CHECKSUM_METHOD_SMIXDRIVER_LIST_SESSIONS
#define UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_CHECKSUM_METHOD_SMIXDRIVER_LIST_SESSIONS
uint16_t uniffi_smix_ffi_checksum_method_smixdriver_list_sessions(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_CHECKSUM_METHOD_SMIXDRIVER_OPEN_SESSION
#define UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_CHECKSUM_METHOD_SMIXDRIVER_OPEN_SESSION
uint16_t uniffi_smix_ffi_checksum_method_smixdriver_open_session(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_CHECKSUM_METHOD_SMIXDRIVER_TREE
#define UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_CHECKSUM_METHOD_SMIXDRIVER_TREE
uint16_t uniffi_smix_ffi_checksum_method_smixdriver_tree(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_CHECKSUM_METHOD_SMIXSESSION_CLOSE
#define UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_CHECKSUM_METHOD_SMIXSESSION_CLOSE
uint16_t uniffi_smix_ffi_checksum_method_smixsession_close(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_CHECKSUM_METHOD_SMIXSESSION_ID
#define UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_CHECKSUM_METHOD_SMIXSESSION_ID
uint16_t uniffi_smix_ffi_checksum_method_smixsession_id(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_CHECKSUM_METHOD_SMIXSESSION_INPUT_TEXT
#define UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_CHECKSUM_METHOD_SMIXSESSION_INPUT_TEXT
uint16_t uniffi_smix_ffi_checksum_method_smixsession_input_text(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_CHECKSUM_METHOD_SMIXSESSION_LAUNCH_APP
#define UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_CHECKSUM_METHOD_SMIXSESSION_LAUNCH_APP
uint16_t uniffi_smix_ffi_checksum_method_smixsession_launch_app(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_CHECKSUM_METHOD_SMIXSESSION_PRESS_KEY
#define UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_CHECKSUM_METHOD_SMIXSESSION_PRESS_KEY
uint16_t uniffi_smix_ffi_checksum_method_smixsession_press_key(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_CHECKSUM_METHOD_SMIXSESSION_RELAUNCH_APP
#define UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_CHECKSUM_METHOD_SMIXSESSION_RELAUNCH_APP
uint16_t uniffi_smix_ffi_checksum_method_smixsession_relaunch_app(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_CHECKSUM_METHOD_SMIXSESSION_RENEW_ACTIVATION
#define UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_CHECKSUM_METHOD_SMIXSESSION_RENEW_ACTIVATION
uint16_t uniffi_smix_ffi_checksum_method_smixsession_renew_activation(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_CHECKSUM_METHOD_SMIXSESSION_SWIPE_ONCE
#define UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_CHECKSUM_METHOD_SMIXSESSION_SWIPE_ONCE
uint16_t uniffi_smix_ffi_checksum_method_smixsession_swipe_once(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_CHECKSUM_METHOD_SMIXSESSION_SYSTEM_POPUPS
#define UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_CHECKSUM_METHOD_SMIXSESSION_SYSTEM_POPUPS
uint16_t uniffi_smix_ffi_checksum_method_smixsession_system_popups(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_CHECKSUM_METHOD_SMIXSESSION_TAP_AT_NORM_COORD
#define UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_CHECKSUM_METHOD_SMIXSESSION_TAP_AT_NORM_COORD
uint16_t uniffi_smix_ffi_checksum_method_smixsession_tap_at_norm_coord(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_CHECKSUM_METHOD_SMIXSESSION_TAP_BY_ID
#define UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_CHECKSUM_METHOD_SMIXSESSION_TAP_BY_ID
uint16_t uniffi_smix_ffi_checksum_method_smixsession_tap_by_id(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_CHECKSUM_METHOD_SMIXSESSION_TERMINATE_APP
#define UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_CHECKSUM_METHOD_SMIXSESSION_TERMINATE_APP
uint16_t uniffi_smix_ffi_checksum_method_smixsession_terminate_app(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_CHECKSUM_CONSTRUCTOR_SMIXDRIVER_NEW
#define UNIFFI_FFIDEF_UNIFFI_SMIX_FFI_CHECKSUM_CONSTRUCTOR_SMIXDRIVER_NEW
uint16_t uniffi_smix_ffi_checksum_constructor_smixdriver_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SMIX_FFI_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_SMIX_FFI_UNIFFI_CONTRACT_VERSION
uint32_t ffi_smix_ffi_uniffi_contract_version(void
    
);
#endif

