//! Embedded Swift runner project sources — solves the CLI-vs-runner
//! version-drift problem described in `.claude/rfcs/1.0.10-*`.
//!
//! `cargo install smix` used to ship only the Rust binary; the Swift
//! `SmixRunner.xcodeproj` + `SmixRunnerCore/` sources had to be
//! obtained separately, and once obtained were never re-synced against
//! subsequent CLI upgrades. This crate carries the runner project as
//! an embedded gzipped tarball so `smix runner up` can verify the
//! on-disk sources match the installed CLI version and re-extract on
//! mismatch.

use std::io;
use std::path::{Path, PathBuf};

use flate2::read::GzDecoder;
use thiserror::Error;

/// Gzipped tarball of the Swift runner project. Baked into the binary
/// at compile time via `include_bytes!`. Regenerated by
/// `scripts/release/build-runner-tarball.sh`.
pub const SOURCES_TAR_GZ: &[u8] = include_bytes!("../data/swift-runner-sources.tar.gz");

/// Version string of the embedded sources — always matches the crate
/// version, which matches the workspace version, which matches the CLI
/// version. Consumers use this as the source-of-truth for
/// `.smix-runner-version` file writes.
pub const SOURCES_VERSION: &str = env!("CARGO_PKG_VERSION");

/// Filename written into `<dst>/.smix-runner-version` after a
/// successful extract. Content is `SOURCES_VERSION` + trailing newline.
pub const VERSION_FILE: &str = ".smix-runner-version";

/// Gzipped tarball of the Android runner project (`:app` only).
///
/// The Android counterpart of [`SOURCES_TAR_GZ`], and the same bargain:
/// what ships is the project, not the artifact. The instrumentation APK
/// is 51 MB; the sources that build it are under 100 KB, and anyone
/// driving an Android device already has the SDK that compiles them —
/// exactly as the iOS path assumes Xcode.
///
/// Until this existed, `runner up --platform android` looked for the APK
/// under the *driven project's* working directory, so it could only ever
/// be found by someone running from a clone of this repository. Everyone
/// who installed smix was told, correctly, that there was no APK — and
/// concluded, incorrectly, that smix had no Android support.
pub const ANDROID_SOURCES_TAR_GZ: &[u8] = include_bytes!("../data/android-runner-sources.tar.gz");

/// Filename written into an extracted Android tree, mirroring
/// [`VERSION_FILE`].
pub const ANDROID_VERSION_FILE: &str = ".smix-android-runner-version";

/// Digest of the embedded Android sources. See [`sources_digest`] for
/// why the version alone cannot answer "are these the same bytes".
#[must_use]
pub fn android_sources_digest() -> u64 {
    let mut hash: u64 = 0xcbf2_9ce4_8422_2325;
    for b in ANDROID_SOURCES_TAR_GZ {
        hash ^= u64::from(*b);
        hash = hash.wrapping_mul(0x100_0000_01b3);
    }
    hash
}

/// The stamp written beside an extracted Android tree.
#[must_use]
pub fn android_version_stamp() -> String {
    format!("{SOURCES_VERSION} {:016x}", android_sources_digest())
}

/// Extract the Android runner project to `dst`, replacing it when the
/// embedded sources differ from what is already there.
///
/// Simpler than [`extract_to`]: there is no xcframework to carry across
/// and no backup rotation, because nothing in the tree is expensive to
/// reproduce — it is 96 KB of gradle project, and the build output lives
/// under `build/` which this never touches.
///
/// # Errors
///
/// I/O failures reading the destination or unpacking the archive.
pub fn extract_android_to(dst: &Path) -> Result<bool, ExtractError> {
    let stamp_path = dst.join(ANDROID_VERSION_FILE);
    let installed = std::fs::read_to_string(&stamp_path).ok();
    if installed.as_deref().map(str::trim) == Some(android_version_stamp().as_str()) {
        return Ok(false);
    }
    std::fs::create_dir_all(dst)
        .map_err(|e| ExtractError::io(format!("creating {}", dst.display()), e))?;
    let gz = GzDecoder::new(ANDROID_SOURCES_TAR_GZ);
    let mut ar = tar::Archive::new(gz);
    ar.set_preserve_permissions(true);
    ar.set_overwrite(true);
    for entry in ar
        .entries()
        .map_err(|e| ExtractError::io("reading android tar entries", e))?
    {
        let mut entry = entry.map_err(|e| ExtractError::io("reading android tar entry", e))?;
        entry
            .unpack_in(dst)
            .map_err(|e| ExtractError::io("unpacking android sources", e))?;
    }
    std::fs::write(&stamp_path, format!("{}\n", android_version_stamp()))
        .map_err(|e| ExtractError::io(format!("writing {}", stamp_path.display()), e))?;
    Ok(true)
}

/// A stamp of what is actually installed: the version, and a digest of
/// the bytes it came from.
///
/// The version alone was not enough, and the gap had teeth. Between two
/// releases the version does not move, so a changed Swift source
/// rebuilt into the tarball compared equal to whatever was already on
/// disk and **was never extracted** — the runner on the device kept
/// running the old code while the repo showed the new. The failure is
/// silent in the worst way: the new route simply 404s, which reads as a
/// bug in the caller.
///
/// This is the same species as the source-freeze cycle the tarball was
/// introduced to end (v1.0.10); the tarball fixed distribution and left
/// the staleness test behind.
#[must_use]
pub fn sources_digest() -> u64 {
    // FNV-1a over the embedded tarball. Not a security boundary — the
    // question is "are these the same bytes I extracted last time", and
    // the adversary is a forgetful build, not an attacker.
    let mut hash: u64 = 0xcbf2_9ce4_8422_2325;
    for b in SOURCES_TAR_GZ {
        hash ^= u64::from(*b);
        hash = hash.wrapping_mul(0x100_0000_01b3);
    }
    hash
}

/// The line written to [`VERSION_FILE`]: version and digest together.
#[must_use]
pub fn version_stamp() -> String {
    format!("{SOURCES_VERSION} {:016x}", sources_digest())
}

/// Is an installed stamp the same sources as the embedded ones?
///
/// Accepts a bare version with no digest as **stale**, deliberately: a
/// tree stamped before digests existed cannot be shown equal, and
/// re-extracting once is cheap next to running the wrong runner.
#[must_use]
pub fn stamp_is_current(installed: Option<&str>) -> bool {
    installed.is_some_and(|s| s.trim() == version_stamp())
}

/// Report of an [`extract_to`] call. Useful for the CLI to emit an
/// info banner after auto-sync.
#[derive(Debug, Clone)]
pub struct ExtractReport {
    /// Absolute path the tarball was extracted into.
    pub destination: PathBuf,
    /// Number of files (regular files, not directories) extracted.
    pub file_count: usize,
    /// If the destination was non-empty before extract, the timestamped
    /// backup path where the previous contents were moved. `None` when
    /// destination was empty or missing.
    pub backup: Option<PathBuf>,
    /// Version string written to `.smix-runner-version`. Always equals
    /// [`SOURCES_VERSION`].
    pub version_written: &'static str,
    /// v1.0.10 patch — set when the extract path carried a
    /// `SmixCoreFFI.xcframework/` in the pre-extract tree and we
    /// preserved it into the new tree. Empty when no xcframework was
    /// carried over (fresh install; caller should fetch/build the
    /// xcframework separately).
    pub carried_xcframework_from: Option<PathBuf>,
    /// Older backup trees removed by the rotation, oldest first. Empty
    /// when there was nothing beyond [`BACKUPS_KEPT`] to remove.
    pub pruned_backups: Vec<PathBuf>,
}

/// Subdirectory names within the extract tree that must be preserved
/// across auto-sync because they are big binary artefacts intentionally
/// excluded from the shipped tarball (fetched or built separately). If
/// found in the pre-extract tree, they are moved back into the new
/// tree after extract completes.
/// How many `<dst>.bak-<ts>` trees survive a sync, newest first.
///
/// The backup exists so a bad sync can be walked back, and one is
/// enough for that. Two is the smallest number that still covers "the
/// sync I want to undo is the one before last" — which happens when a
/// re-sync is the thing that revealed the problem.
///
/// It had no bound at all until this was added. A developer machine
/// running smix daily accumulated 48 of them across nine days, 1.8 MB
/// each, holding a share directory at 190 MB. Nothing announced them,
/// nothing removed them, and the tree they protect is 1.8 MB — so the
/// unbounded history cost a hundred times what it insured.
pub const BACKUPS_KEPT: usize = 2;

const CARRIED_ARTEFACTS: &[&str] = &[
    "SmixCoreFFI.xcframework",
    "SmixCoreFFI.xcframework.zip",
    "SmixCoreFFI.xcframework.zip.sha256",
];

/// Errors from [`extract_to`].
#[derive(Debug, Error)]
pub enum ExtractError {
    /// I/O failure during extract, backup, or version-file write.
    #[error("smix-runner-sources: {context}: {source}")]
    Io {
        context: String,
        #[source]
        source: io::Error,
    },
    /// Destination is non-empty and `force` was false. Callers should
    /// either pass `force=true` or resolve the conflict.
    #[error(
        "smix-runner-sources: refusing to overwrite non-empty {0:?} (pass force=true to backup and replace)"
    )]
    DestinationNotEmpty(PathBuf),
}

impl ExtractError {
    fn io<S: Into<String>>(context: S, source: io::Error) -> Self {
        Self::Io {
            context: context.into(),
            source,
        }
    }
}

/// Read `<dst>/.smix-runner-version` and return the trimmed content.
/// Returns `Ok(None)` when the file does not exist. Returns `Err` only
/// on I/O failure other than not-found.
pub fn read_installed_version(dst: &Path) -> Result<Option<String>, ExtractError> {
    let path = dst.join(VERSION_FILE);
    match std::fs::read_to_string(&path) {
        Ok(s) => Ok(Some(s.trim().to_string())),
        Err(e) if e.kind() == io::ErrorKind::NotFound => Ok(None),
        Err(e) => Err(ExtractError::io(format!("reading {}", path.display()), e)),
    }
}

/// Extract the embedded runner sources into `dst`.
///
/// If `dst` is missing or empty, extracts directly. If `dst` is
/// non-empty and `force` is `false`, returns
/// [`ExtractError::DestinationNotEmpty`]. If `dst` is non-empty and
/// `force` is `true`, moves the existing contents to `<dst>.bak-<ts>`
/// alongside `dst` (never inside — avoids the "delete self" trap) and
/// then extracts fresh.
///
/// After a successful extract, writes `<dst>/.smix-runner-version`
/// containing [`SOURCES_VERSION`] + newline. The CLI cascade uses this
/// file to detect version drift on subsequent boots.
pub fn extract_to(dst: &Path, force: bool) -> Result<ExtractReport, ExtractError> {
    let dst_exists = dst.exists();
    let is_empty = if dst_exists {
        is_directory_empty(dst)
            .map_err(|e| ExtractError::io(format!("scanning {}", dst.display()), e))?
    } else {
        true
    };

    let mut backup: Option<PathBuf> = None;
    if dst_exists && !is_empty {
        if !force {
            return Err(ExtractError::DestinationNotEmpty(dst.to_path_buf()));
        }
        let bak = timestamped_backup_path(dst);
        std::fs::rename(dst, &bak).map_err(|e| {
            ExtractError::io(
                format!("backing up {} to {}", dst.display(), bak.display()),
                e,
            )
        })?;
        backup = Some(bak);
    }

    std::fs::create_dir_all(dst)
        .map_err(|e| ExtractError::io(format!("mkdir -p {}", dst.display()), e))?;

    // v1.0.10 patch — before writing the fresh tarball contents, carry
    // over the excluded-from-tarball binary artefacts (SmixCoreFFI
    // xcframework and its sidecars) from the backup tree. Without this,
    // an auto-sync leaves the runner project unbuildable because
    // `Package.swift` declares a `.binaryTarget(path: "SmixCoreFFI.
    // xcframework")` that xcodebuild dereferences at `Resolve Package
    // Graph` time.
    let mut carried_xcframework_from: Option<PathBuf> = None;
    if let Some(bak) = backup.as_ref() {
        for artefact in CARRIED_ARTEFACTS {
            let src = bak.join(artefact);
            if src.exists() {
                let dst_path = dst.join(artefact);
                // `rename` is atomic within the same filesystem; the
                // backup is a sibling of the destination so this is
                // fast. Fallback to recursive copy if rename fails
                // (e.g., different volumes — unlikely under XDG basedir
                // but defensive).
                if std::fs::rename(&src, &dst_path).is_err() {
                    copy_dir_recursive(&src, &dst_path).map_err(|e| {
                        ExtractError::io(
                            format!("copying {} to {}", src.display(), dst_path.display()),
                            e,
                        )
                    })?;
                }
                if carried_xcframework_from.is_none() {
                    carried_xcframework_from = Some(bak.clone());
                }
            }
        }
    }

    let gz = GzDecoder::new(SOURCES_TAR_GZ);
    let mut ar = tar::Archive::new(gz);
    ar.set_preserve_permissions(true);
    ar.set_overwrite(true);

    let mut file_count = 0usize;
    for entry in ar
        .entries()
        .map_err(|e| ExtractError::io("reading tar entries", e))?
    {
        let mut entry = entry.map_err(|e| ExtractError::io("reading tar entry", e))?;
        let is_file = entry.header().entry_type().is_file();
        entry.unpack_in(dst).map_err(|e| {
            ExtractError::io(
                format!(
                    "unpacking {}",
                    entry
                        .path()
                        .map(|p| p.display().to_string())
                        .unwrap_or_else(|_| "<unknown>".to_string())
                ),
                e,
            )
        })?;
        if is_file {
            file_count += 1;
        }
    }

    let version_path = dst.join(VERSION_FILE);
    // Version *and* digest: between releases the version does not move,
    // so it alone cannot tell a rebuilt tarball from the one already
    // here. See `sources_digest`.
    std::fs::write(&version_path, format!("{}\n", version_stamp()))
        .map_err(|e| ExtractError::io(format!("writing {}", version_path.display()), e))?;

    // Last, so a rotation failure cannot cost the tree that was just
    // extracted. The message has to say that outright: by this point
    // the runner IS installed, and an error that reads like "install
    // failed" would send someone to re-run a sync that worked.
    let pruned = prune_backups(dst, BACKUPS_KEPT).map_err(|e| {
        ExtractError::io(
            format!(
                "runner sources extracted to {} successfully, but pruning old \
                 backups beside it failed",
                dst.display()
            ),
            e,
        )
    })?;

    Ok(ExtractReport {
        destination: dst.to_path_buf(),
        file_count,
        backup,
        version_written: SOURCES_VERSION,
        carried_xcframework_from,
        pruned_backups: pruned,
    })
}

fn copy_dir_recursive(src: &Path, dst: &Path) -> io::Result<()> {
    if src.is_file() {
        if let Some(parent) = dst.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::copy(src, dst)?;
        return Ok(());
    }
    std::fs::create_dir_all(dst)?;
    for entry in std::fs::read_dir(src)? {
        let entry = entry?;
        let ft = entry.file_type()?;
        let src_p = entry.path();
        let dst_p = dst.join(entry.file_name());
        if ft.is_dir() {
            copy_dir_recursive(&src_p, &dst_p)?;
        } else {
            std::fs::copy(&src_p, &dst_p)?;
        }
    }
    Ok(())
}

fn is_directory_empty(p: &Path) -> io::Result<bool> {
    let mut iter = std::fs::read_dir(p)?;
    Ok(iter.next().is_none())
}

/// Existing `<dst>.bak-<ts>` trees, oldest first.
///
/// Ordered by the timestamp in the name rather than by mtime: the name
/// is what the backup was called at creation, while an mtime can be
/// changed by anything that touches the tree afterwards. A directory
/// whose suffix is not a number is not one of ours and is left alone.
fn existing_backups(dst: &Path) -> io::Result<Vec<(u64, PathBuf)>> {
    let parent = dst.parent().unwrap_or_else(|| Path::new("."));
    let base = dst
        .file_name()
        .map(|s| s.to_string_lossy().to_string())
        .unwrap_or_else(|| "runner".to_string());
    let prefix = format!("{base}.bak-");

    let mut found = Vec::new();
    let entries = match std::fs::read_dir(parent) {
        Ok(entries) => entries,
        Err(e) if e.kind() == io::ErrorKind::NotFound => return Ok(found),
        Err(e) => return Err(e),
    };
    for entry in entries {
        let entry = entry?;
        let name = entry.file_name().to_string_lossy().to_string();
        let Some(suffix) = name.strip_prefix(&prefix) else {
            continue;
        };
        let Ok(stamp) = suffix.parse::<u64>() else {
            continue;
        };
        if entry.path().is_dir() {
            found.push((stamp, entry.path()));
        }
    }
    found.sort_by_key(|(stamp, _)| *stamp);
    Ok(found)
}

/// Delete all but the newest `keep` backup trees. Returns what went,
/// oldest first.
fn prune_backups(dst: &Path, keep: usize) -> io::Result<Vec<PathBuf>> {
    let backups = existing_backups(dst)?;
    let excess = backups.len().saturating_sub(keep);
    let mut removed = Vec::new();
    for (_, path) in backups.into_iter().take(excess) {
        std::fs::remove_dir_all(&path)?;
        removed.push(path);
    }
    Ok(removed)
}

fn timestamped_backup_path(dst: &Path) -> PathBuf {
    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);
    let parent = dst.parent().unwrap_or_else(|| Path::new("."));
    let base = dst
        .file_name()
        .map(|s| s.to_string_lossy().to_string())
        .unwrap_or_else(|| "runner".to_string());
    parent.join(format!("{base}.bak-{now}"))
}
