//! Embedded Swift runner project sources — solves the CLI-vs-runner
//! version-drift problem described in `.claude/rfcs/1.0.10-*`.
//!
//! `cargo install smix` used to ship only the Rust binary; the Swift
//! `SmixRunner.xcodeproj` + `SmixRunnerCore/` sources had to be
//! obtained separately, and once obtained were never re-synced against
//! subsequent CLI upgrades. This crate carries the runner project as
//! an embedded gzipped tarball so `smix runner up` can verify the
//! on-disk sources match the installed CLI version and re-extract on
//! mismatch.

use std::io;
use std::path::{Path, PathBuf};

use flate2::read::GzDecoder;
use thiserror::Error;

/// Gzipped tarball of the Swift runner project. Baked into the binary
/// at compile time via `include_bytes!`. Regenerated by
/// `scripts/release/build-runner-tarball.sh`.
pub const SOURCES_TAR_GZ: &[u8] = include_bytes!("../data/swift-runner-sources.tar.gz");

/// Version string of the embedded sources — always matches the crate
/// version, which matches the workspace version, which matches the CLI
/// version. Consumers use this as the source-of-truth for
/// `.smix-runner-version` file writes.
pub const SOURCES_VERSION: &str = env!("CARGO_PKG_VERSION");

/// Filename written into `<dst>/.smix-runner-version` after a
/// successful extract. Content is `SOURCES_VERSION` + trailing newline.
pub const VERSION_FILE: &str = ".smix-runner-version";

/// Report of an [`extract_to`] call. Useful for the CLI to emit an
/// info banner after auto-sync.
#[derive(Debug, Clone)]
pub struct ExtractReport {
    /// Absolute path the tarball was extracted into.
    pub destination: PathBuf,
    /// Number of files (regular files, not directories) extracted.
    pub file_count: usize,
    /// If the destination was non-empty before extract, the timestamped
    /// backup path where the previous contents were moved. `None` when
    /// destination was empty or missing.
    pub backup: Option<PathBuf>,
    /// Version string written to `.smix-runner-version`. Always equals
    /// [`SOURCES_VERSION`].
    pub version_written: &'static str,
}

/// Errors from [`extract_to`].
#[derive(Debug, Error)]
pub enum ExtractError {
    /// I/O failure during extract, backup, or version-file write.
    #[error("smix-runner-sources: {context}: {source}")]
    Io {
        context: String,
        #[source]
        source: io::Error,
    },
    /// Destination is non-empty and `force` was false. Callers should
    /// either pass `force=true` or resolve the conflict.
    #[error(
        "smix-runner-sources: refusing to overwrite non-empty {0:?} (pass force=true to backup and replace)"
    )]
    DestinationNotEmpty(PathBuf),
}

impl ExtractError {
    fn io<S: Into<String>>(context: S, source: io::Error) -> Self {
        Self::Io {
            context: context.into(),
            source,
        }
    }
}

/// Read `<dst>/.smix-runner-version` and return the trimmed content.
/// Returns `Ok(None)` when the file does not exist. Returns `Err` only
/// on I/O failure other than not-found.
pub fn read_installed_version(dst: &Path) -> Result<Option<String>, ExtractError> {
    let path = dst.join(VERSION_FILE);
    match std::fs::read_to_string(&path) {
        Ok(s) => Ok(Some(s.trim().to_string())),
        Err(e) if e.kind() == io::ErrorKind::NotFound => Ok(None),
        Err(e) => Err(ExtractError::io(
            format!("reading {}", path.display()),
            e,
        )),
    }
}

/// Extract the embedded runner sources into `dst`.
///
/// If `dst` is missing or empty, extracts directly. If `dst` is
/// non-empty and `force` is `false`, returns
/// [`ExtractError::DestinationNotEmpty`]. If `dst` is non-empty and
/// `force` is `true`, moves the existing contents to `<dst>.bak-<ts>`
/// alongside `dst` (never inside — avoids the "delete self" trap) and
/// then extracts fresh.
///
/// After a successful extract, writes `<dst>/.smix-runner-version`
/// containing [`SOURCES_VERSION`] + newline. The CLI cascade uses this
/// file to detect version drift on subsequent boots.
pub fn extract_to(dst: &Path, force: bool) -> Result<ExtractReport, ExtractError> {
    let dst_exists = dst.exists();
    let is_empty = if dst_exists {
        is_directory_empty(dst).map_err(|e| ExtractError::io(format!("scanning {}", dst.display()), e))?
    } else {
        true
    };

    let mut backup: Option<PathBuf> = None;
    if dst_exists && !is_empty {
        if !force {
            return Err(ExtractError::DestinationNotEmpty(dst.to_path_buf()));
        }
        let bak = timestamped_backup_path(dst);
        std::fs::rename(dst, &bak).map_err(|e| {
            ExtractError::io(
                format!("backing up {} to {}", dst.display(), bak.display()),
                e,
            )
        })?;
        backup = Some(bak);
    }

    std::fs::create_dir_all(dst)
        .map_err(|e| ExtractError::io(format!("mkdir -p {}", dst.display()), e))?;

    let gz = GzDecoder::new(SOURCES_TAR_GZ);
    let mut ar = tar::Archive::new(gz);
    ar.set_preserve_permissions(true);
    ar.set_overwrite(true);

    let mut file_count = 0usize;
    for entry in ar
        .entries()
        .map_err(|e| ExtractError::io("reading tar entries", e))?
    {
        let mut entry =
            entry.map_err(|e| ExtractError::io("reading tar entry", e))?;
        let is_file = entry.header().entry_type().is_file();
        entry.unpack_in(dst).map_err(|e| {
            ExtractError::io(
                format!(
                    "unpacking {}",
                    entry
                        .path()
                        .map(|p| p.display().to_string())
                        .unwrap_or_else(|_| "<unknown>".to_string())
                ),
                e,
            )
        })?;
        if is_file {
            file_count += 1;
        }
    }

    let version_path = dst.join(VERSION_FILE);
    std::fs::write(&version_path, format!("{SOURCES_VERSION}\n")).map_err(|e| {
        ExtractError::io(format!("writing {}", version_path.display()), e)
    })?;

    Ok(ExtractReport {
        destination: dst.to_path_buf(),
        file_count,
        backup,
        version_written: SOURCES_VERSION,
    })
}

fn is_directory_empty(p: &Path) -> io::Result<bool> {
    let mut iter = std::fs::read_dir(p)?;
    Ok(iter.next().is_none())
}

fn timestamped_backup_path(dst: &Path) -> PathBuf {
    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);
    let parent = dst.parent().unwrap_or_else(|| Path::new("."));
    let base = dst.file_name().map(|s| s.to_string_lossy().to_string()).unwrap_or_else(|| "runner".to_string());
    parent.join(format!("{base}.bak-{now}"))
}
