//! Embedded Swift runner project sources — solves the CLI-vs-runner
//! version-drift problem.
//!
//! `cargo install smix` used to ship only the Rust binary; the Swift
//! `SmixRunner.xcodeproj` + `SmixRunnerCore/` sources had to be
//! obtained separately, and once obtained were never re-synced against
//! subsequent CLI upgrades. This crate carries the runner project as
//! an embedded gzipped tarball so `smix runner up` can verify the
//! on-disk sources match the installed CLI version and re-extract on
//! mismatch.

use std::io;
use std::path::{Path, PathBuf};

use flate2::read::GzDecoder;
use thiserror::Error;

mod tree;
pub use tree::{Ensured, LAST_USED_FILE, RunnerPlatform, ensure_tree, tree_dir};

/// Gzipped tarball of the Swift runner project. Baked into the binary
/// at compile time via `include_bytes!`. Regenerated by
/// `scripts/release/build-runner-tarball.sh`.
pub const SOURCES_TAR_GZ: &[u8] = include_bytes!("../data/swift-runner-sources.tar.gz");

/// Version string of the embedded sources — always matches the crate
/// version, which matches the workspace version, which matches the CLI
/// version. Consumers use this as the source-of-truth for
/// `.smix-runner-version` file writes.
pub const SOURCES_VERSION: &str = env!("CARGO_PKG_VERSION");

/// Filename written into `<dst>/.smix-runner-version` after a
/// successful extract. Content is `SOURCES_VERSION` + trailing newline.
pub const VERSION_FILE: &str = ".smix-runner-version";

/// Gzipped tarball of the Android runner project (`:app` only).
///
/// The Android counterpart of [`SOURCES_TAR_GZ`], and the same bargain:
/// what ships is the project, not the artifact. The instrumentation APK
/// is 51 MB; the sources that build it are under 100 KB, and anyone
/// driving an Android device already has the SDK that compiles them —
/// exactly as the iOS path assumes Xcode.
///
/// Until this existed, `runner up --platform android` looked for the APK
/// under the *driven project's* working directory, so it could only ever
/// be found by someone running from a clone of this repository. Everyone
/// who installed smix was told, correctly, that there was no APK — and
/// concluded, incorrectly, that smix had no Android support.
pub const ANDROID_SOURCES_TAR_GZ: &[u8] = include_bytes!("../data/android-runner-sources.tar.gz");

/// Filename written into an extracted Android tree, mirroring
/// [`VERSION_FILE`].
pub const ANDROID_VERSION_FILE: &str = ".smix-android-runner-version";

/// Digest of the embedded Android sources. See [`sources_digest`] for
/// why the version alone cannot answer "are these the same bytes".
#[must_use]
pub fn android_sources_digest() -> u64 {
    let mut hash: u64 = 0xcbf2_9ce4_8422_2325;
    for b in ANDROID_SOURCES_TAR_GZ {
        hash ^= u64::from(*b);
        hash = hash.wrapping_mul(0x100_0000_01b3);
    }
    hash
}

/// The stamp written beside an extracted Android tree.
#[must_use]
pub fn android_version_stamp() -> String {
    format!("{SOURCES_VERSION} {:016x}", android_sources_digest())
}

/// A stamp of what is actually installed: the version, and a digest of
/// the bytes it came from.
///
/// The version alone was not enough, and the gap had teeth. Between two
/// releases the version does not move, so a changed Swift source
/// rebuilt into the tarball compared equal to whatever was already on
/// disk and **was never extracted** — the runner on the device kept
/// running the old code while the repo showed the new. The failure is
/// silent in the worst way: the new route simply 404s, which reads as a
/// bug in the caller.
///
/// This is the same species as the source-freeze cycle the tarball was
/// introduced to end (v1.0.10); the tarball fixed distribution and left
/// the staleness test behind.
#[must_use]
pub fn sources_digest() -> u64 {
    // FNV-1a over the embedded tarball. Not a security boundary — the
    // question is "are these the same bytes I extracted last time", and
    // the adversary is a forgetful build, not an attacker.
    let mut hash: u64 = 0xcbf2_9ce4_8422_2325;
    for b in SOURCES_TAR_GZ {
        hash ^= u64::from(*b);
        hash = hash.wrapping_mul(0x100_0000_01b3);
    }
    hash
}

/// The line written to [`VERSION_FILE`]: version and digest together.
#[must_use]
pub fn version_stamp() -> String {
    format!("{SOURCES_VERSION} {:016x}", sources_digest())
}

/// Is an installed stamp the same sources as the embedded ones?
///
/// Accepts a bare version with no digest as **stale**, deliberately: a
/// tree stamped before digests existed cannot be shown equal, and
/// re-extracting once is cheap next to running the wrong runner.
#[must_use]
pub fn stamp_is_current(installed: Option<&str>) -> bool {
    installed.is_some_and(|s| s.trim() == version_stamp())
}

/// Report of an [`extract_to`] call. Useful for the CLI to emit an
/// info banner after auto-sync.
#[derive(Debug, Clone)]
pub struct ExtractReport {
    /// Absolute path the tarball was extracted into.
    pub destination: PathBuf,
    /// Number of files (regular files, not directories) extracted.
    pub file_count: usize,
    /// If the destination was non-empty before extract, the timestamped
    /// backup path where the previous contents were moved. `None` when
    /// destination was empty or missing.
    pub backup: Option<PathBuf>,
    /// Version string written to `.smix-runner-version`. Always equals
    /// [`SOURCES_VERSION`].
    pub version_written: &'static str,
    /// v1.0.10 patch — set when the extract path carried a
    /// `SmixCoreFFI.xcframework/` in the pre-extract tree and we
    /// preserved it into the new tree. Empty when no xcframework was
    /// carried over (fresh install; caller should fetch/build the
    /// xcframework separately).
    pub carried_xcframework_from: Option<PathBuf>,
    /// Older backup trees removed by the rotation, oldest first. Empty
    /// when there was nothing beyond [`BACKUPS_KEPT`] to remove.
    pub pruned_backups: Vec<PathBuf>,
}

/// Subdirectory names within the extract tree that must be preserved
/// across auto-sync because they are big binary artefacts intentionally
/// excluded from the shipped tarball (fetched or built separately). If
/// found in the pre-extract tree, they are moved back into the new
/// tree after extract completes.
/// How many `<dst>.bak-<ts>` trees survive a sync, newest first.
///
/// The backup exists so a bad sync can be walked back, and one is
/// enough for that. Two is the smallest number that still covers "the
/// sync I want to undo is the one before last" — which happens when a
/// re-sync is the thing that revealed the problem.
///
/// It had no bound at all until this was added. A developer machine
/// running smix daily accumulated 48 of them across nine days, 1.8 MB
/// each, holding a share directory at 190 MB. Nothing announced them,
/// nothing removed them, and the tree they protect is 1.8 MB — so the
/// unbounded history cost a hundred times what it insured.
pub const BACKUPS_KEPT: usize = 2;

const CARRIED_ARTEFACTS: &[&str] = &[
    "SmixCoreFFI.xcframework",
    "SmixCoreFFI.xcframework.zip",
    "SmixCoreFFI.xcframework.zip.sha256",
];

/// Errors from [`extract_to`].
#[derive(Debug, Error)]
pub enum ExtractError {
    /// I/O failure during extract, backup, or version-file write.
    #[error("smix-runner-sources: {context}: {source}")]
    Io {
        context: String,
        #[source]
        source: io::Error,
    },
    /// Destination is non-empty and `force` was false. Callers should
    /// either pass `force=true` or resolve the conflict.
    #[error(
        "smix-runner-sources: refusing to overwrite non-empty {0:?} (pass force=true to backup and replace)"
    )]
    DestinationNotEmpty(PathBuf),
}

impl ExtractError {
    fn io<S: Into<String>>(context: S, source: io::Error) -> Self {
        Self::Io {
            context: context.into(),
            source,
        }
    }
}

/// Read `<dst>/.smix-runner-version` and return the trimmed content.
/// Returns `Ok(None)` when the file does not exist. Returns `Err` only
/// on I/O failure other than not-found.
pub fn read_installed_version(dst: &Path) -> Result<Option<String>, ExtractError> {
    let path = dst.join(VERSION_FILE);
    match std::fs::read_to_string(&path) {
        Ok(s) => Ok(Some(s.trim().to_string())),
        Err(e) if e.kind() == io::ErrorKind::NotFound => Ok(None),
        Err(e) => Err(ExtractError::io(format!("reading {}", path.display()), e)),
    }
}

/// Extract the embedded runner sources into `dst`.
///
/// If `dst` is missing or empty, extracts directly. If `dst` is
/// non-empty and `force` is `false`, returns
/// [`ExtractError::DestinationNotEmpty`]. If `dst` is non-empty and
/// `force` is `true`, moves the existing contents to `<dst>.bak-<ts>`
/// alongside `dst` (never inside — avoids the "delete self" trap) and
/// then extracts fresh.
///
/// After a successful extract, writes `<dst>/.smix-runner-version`
/// containing [`SOURCES_VERSION`] + newline. The CLI cascade uses this
/// file to detect version drift on subsequent boots.
pub fn extract_to(dst: &Path, force: bool) -> Result<ExtractReport, ExtractError> {
    let is_empty = if dst.exists() {
        is_directory_empty(dst)
            .map_err(|e| ExtractError::io(format!("scanning {}", dst.display()), e))?
    } else {
        true
    };
    if !is_empty && !force {
        return Err(ExtractError::DestinationNotEmpty(dst.to_path_buf()));
    }

    // The xcframework and its sidecars are excluded from the tarball
    // (fetched or built separately), and `Package.swift` declares a
    // `.binaryTarget(path: "SmixCoreFFI.xcframework")` that xcodebuild
    // dereferences at `Resolve Package Graph` time — a sync that dropped
    // them would leave the project unbuildable.
    let installed = install_tree(
        dst,
        SOURCES_TAR_GZ,
        VERSION_FILE,
        &version_stamp(),
        CARRIED_ARTEFACTS,
    )?;
    let carried_xcframework_from = if installed.carried {
        installed.backup.clone()
    } else {
        None
    };

    // Last, so a rotation failure cannot cost the tree that was just
    // extracted. The message has to say that outright: by this point
    // the runner IS installed, and an error that reads like "install
    // failed" would send someone to re-run a sync that worked.
    let pruned = prune_backups(dst, BACKUPS_KEPT).map_err(|e| {
        ExtractError::io(
            format!(
                "runner sources extracted to {} successfully, but pruning old \
                 backups beside it failed",
                dst.display()
            ),
            e,
        )
    })?;

    Ok(ExtractReport {
        destination: dst.to_path_buf(),
        file_count: installed.file_count,
        backup: installed.backup,
        version_written: SOURCES_VERSION,
        carried_xcframework_from,
        pruned_backups: pruned,
    })
}

/// What [`install_tree`] did.
struct Installed {
    file_count: usize,
    /// Where the tree it replaced went, if there was one.
    backup: Option<PathBuf>,
    /// Whether anything named in `carry` came across from that tree.
    carried: bool,
}

/// How many times a swap is tried when another installer keeps putting its
/// own tree into the gap. Each round leaves a whole tree in place, so a
/// loss here is a clean one; the bound only stops two installers trading
/// the directory forever.
const SWAP_ATTEMPTS: usize = 16;

/// Put `archive` at `dst` as one whole tree: unpacked beside it, stamped,
/// then moved in.
///
/// Every state `dst` passes through is a complete tree — the old one, or
/// the new one, never a mixture — so a reader, a crash, or a second
/// installer working at the same moment meets one version or the other.
/// With two installers of different sources the last to move in wins, and
/// its stamp is the one in the directory. Within that there is a moment
/// with no `dst` at all (between moving the old tree out and the new one
/// in); a reader then finds nothing rather than something wrong.
///
/// `carry` names paths in the old tree that do not ship and are kept:
/// moved into the new tree just before the swap. The old tree becomes a
/// `<dst>.bak-<n>` beside it; rotation is the caller's.
fn install_tree(
    dst: &Path,
    archive: &[u8],
    stamp_file: &str,
    stamp: &str,
    carry: &[&str],
) -> Result<Installed, ExtractError> {
    let parent = dst.parent().unwrap_or_else(|| Path::new("."));
    std::fs::create_dir_all(parent)
        .map_err(|e| ExtractError::io(format!("mkdir -p {}", parent.display()), e))?;
    let staging = Staging::beside(dst)?;

    let file_count = unpack(archive, staging.path())?;
    let stamp_path = staging.path().join(stamp_file);
    std::fs::write(&stamp_path, format!("{stamp}\n"))
        .map_err(|e| ExtractError::io(format!("writing {}", stamp_path.display()), e))?;

    let mut carried = false;
    for _ in 0..SWAP_ATTEMPTS {
        carried |= carry_into(dst, staging.path(), carry)?;
        // An empty directory is nothing to keep: removed, not backed up.
        if is_directory_empty(dst).unwrap_or(false) {
            match std::fs::remove_dir(dst) {
                Ok(()) => {}
                Err(e) if e.kind() == io::ErrorKind::NotFound => {}
                // Filled in the meantime by another installer: back it up below.
                Err(e) if is_occupied(&e) => {}
                Err(e) => {
                    return Err(ExtractError::io(
                        format!("removing empty {}", dst.display()),
                        e,
                    ));
                }
            }
        }
        let aside = fresh_backup_path(dst);
        let backup = match std::fs::rename(dst, &aside) {
            Ok(()) => Some(aside),
            Err(e) if e.kind() == io::ErrorKind::NotFound => None,
            // Another installer took that backup name in the same instant.
            Err(e) if is_occupied(&e) => continue,
            Err(e) => {
                return Err(ExtractError::io(
                    format!("moving {} aside", dst.display()),
                    e,
                ));
            }
        };
        match std::fs::rename(staging.path(), dst) {
            Ok(()) => {
                staging.moved_in();
                return Ok(Installed {
                    file_count,
                    backup,
                    carried,
                });
            }
            // Someone else's tree went in between our two moves. It is a
            // whole tree too; go round and put ours over it.
            Err(e) if is_occupied(&e) => {}
            Err(e) => {
                return Err(ExtractError::io(
                    format!("moving {} into {}", staging.path().display(), dst.display()),
                    e,
                ));
            }
        }
    }
    Err(ExtractError::io(
        format!(
            "moving a new tree into {}: another installer replaced it {SWAP_ATTEMPTS} \
             times in a row",
            dst.display()
        ),
        io::Error::from(io::ErrorKind::ResourceBusy),
    ))
}

/// Unpack a gzipped tarball into `into`; returns how many regular files.
pub(crate) fn unpack(archive: &[u8], into: &Path) -> Result<usize, ExtractError> {
    let mut ar = tar::Archive::new(GzDecoder::new(archive));
    ar.set_preserve_permissions(true);
    ar.set_overwrite(true);
    let mut file_count = 0usize;
    for entry in ar
        .entries()
        .map_err(|e| ExtractError::io("reading tar entries", e))?
    {
        let mut entry = entry.map_err(|e| ExtractError::io("reading tar entry", e))?;
        let is_file = entry.header().entry_type().is_file();
        entry.unpack_in(into).map_err(|e| {
            ExtractError::io(
                format!(
                    "unpacking {}",
                    entry
                        .path()
                        .map(|p| p.display().to_string())
                        .unwrap_or_else(|_| "<unknown>".to_string())
                ),
                e,
            )
        })?;
        if is_file {
            file_count += 1;
        }
    }
    Ok(file_count)
}

/// Move each `carry` path that `from` has and `into` does not. Returns
/// whether any moved.
fn carry_into(from: &Path, into: &Path, carry: &[&str]) -> Result<bool, ExtractError> {
    let mut any = false;
    for rel in carry {
        let src = from.join(rel);
        let dst = into.join(rel);
        if !src.exists() || dst.exists() {
            continue;
        }
        if let Some(parent) = dst.parent() {
            std::fs::create_dir_all(parent)
                .map_err(|e| ExtractError::io(format!("mkdir -p {}", parent.display()), e))?;
        }
        // Same parent directory, so the same filesystem: a rename. The
        // copy is for the case where it is not (a bind mount inside the
        // share directory), where rename answers EXDEV.
        if std::fs::rename(&src, &dst).is_err() {
            copy_dir_recursive(&src, &dst).map_err(|e| {
                ExtractError::io(format!("copying {} to {}", src.display(), dst.display()), e)
            })?;
        }
        any = true;
    }
    Ok(any)
}

/// A rename refused because the target is taken.
pub(crate) fn is_occupied(e: &io::Error) -> bool {
    matches!(
        e.kind(),
        io::ErrorKind::AlreadyExists | io::ErrorKind::DirectoryNotEmpty
    )
}

/// The directory a new tree is built in, beside the destination so moving
/// it in is a rename. Removed on drop unless it was moved in — an unpack
/// that fails halfway leaves nothing behind.
pub(crate) struct Staging {
    path: PathBuf,
    moved: std::cell::Cell<bool>,
}

impl Staging {
    pub(crate) fn beside(dst: &Path) -> Result<Self, ExtractError> {
        let parent = dst.parent().unwrap_or_else(|| Path::new("."));
        let base = dst
            .file_name()
            .map(|s| s.to_string_lossy().to_string())
            .unwrap_or_else(|| "runner".to_string());
        let nanos = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_nanos())
            .unwrap_or(0);
        // Leading dot and a pid: never mistaken for the tree or a backup.
        // The pid alone does not keep two installers apart when they are
        // threads of one process, and the clock does not either: on Linux
        // two threads read the same nanosecond and the second `mkdir`
        // failed (measured 2026-09-25). A per-process counter does.
        static NEXT: std::sync::atomic::AtomicU64 = std::sync::atomic::AtomicU64::new(0);
        let seq = NEXT.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
        let path = parent.join(format!(
            ".{base}.staging-{}-{nanos}-{seq}",
            std::process::id()
        ));
        std::fs::create_dir(&path)
            .map_err(|e| ExtractError::io(format!("mkdir {}", path.display()), e))?;
        Ok(Self {
            path,
            moved: std::cell::Cell::new(false),
        })
    }

    pub(crate) fn path(&self) -> &Path {
        &self.path
    }

    pub(crate) fn moved_in(&self) {
        self.moved.set(true);
    }
}

impl Drop for Staging {
    fn drop(&mut self) {
        if !self.moved.get() {
            // A failed install's scratch. The error that got us here is
            // already on its way to the caller; this removal failing would
            // leave a dot-directory, which is not worth replacing it with.
            let _ = std::fs::remove_dir_all(&self.path);
        }
    }
}

fn copy_dir_recursive(src: &Path, dst: &Path) -> io::Result<()> {
    if src.is_file() {
        if let Some(parent) = dst.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::copy(src, dst)?;
        return Ok(());
    }
    std::fs::create_dir_all(dst)?;
    for entry in std::fs::read_dir(src)? {
        let entry = entry?;
        let ft = entry.file_type()?;
        let src_p = entry.path();
        let dst_p = dst.join(entry.file_name());
        if ft.is_dir() {
            copy_dir_recursive(&src_p, &dst_p)?;
        } else {
            std::fs::copy(&src_p, &dst_p)?;
        }
    }
    Ok(())
}

fn is_directory_empty(p: &Path) -> io::Result<bool> {
    let mut iter = std::fs::read_dir(p)?;
    Ok(iter.next().is_none())
}

/// Existing `<dst>.bak-<ts>` trees, oldest first.
///
/// Ordered by the timestamp in the name rather than by mtime: the name
/// is what the backup was called at creation, while an mtime can be
/// changed by anything that touches the tree afterwards. A directory
/// whose suffix is not a number is not one of ours and is left alone.
fn existing_backups(dst: &Path) -> io::Result<Vec<(u64, PathBuf)>> {
    let parent = dst.parent().unwrap_or_else(|| Path::new("."));
    let base = dst
        .file_name()
        .map(|s| s.to_string_lossy().to_string())
        .unwrap_or_else(|| "runner".to_string());
    let prefix = format!("{base}.bak-");

    let mut found = Vec::new();
    let entries = match std::fs::read_dir(parent) {
        Ok(entries) => entries,
        Err(e) if e.kind() == io::ErrorKind::NotFound => return Ok(found),
        Err(e) => return Err(e),
    };
    for entry in entries {
        let entry = entry?;
        let name = entry.file_name().to_string_lossy().to_string();
        let Some(suffix) = name.strip_prefix(&prefix) else {
            continue;
        };
        let Ok(stamp) = suffix.parse::<u64>() else {
            continue;
        };
        if entry.path().is_dir() {
            found.push((stamp, entry.path()));
        }
    }
    found.sort_by_key(|(stamp, _)| *stamp);
    Ok(found)
}

/// Delete all but the newest `keep` backup trees. Returns what went,
/// oldest first.
fn prune_backups(dst: &Path, keep: usize) -> io::Result<Vec<PathBuf>> {
    let backups = existing_backups(dst)?;
    let excess = backups.len().saturating_sub(keep);
    let mut removed = Vec::new();
    for (_, path) in backups.into_iter().take(excess) {
        std::fs::remove_dir_all(&path)?;
        removed.push(path);
    }
    Ok(removed)
}

/// A `<dst>.bak-<n>` that does not exist yet: seconds since the epoch, or
/// the next free number after it when two syncs land in one second.
fn fresh_backup_path(dst: &Path) -> PathBuf {
    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);
    let parent = dst.parent().unwrap_or_else(|| Path::new("."));
    let base = dst
        .file_name()
        .map(|s| s.to_string_lossy().to_string())
        .unwrap_or_else(|| "runner".to_string());
    let mut n = now;
    loop {
        let candidate = parent.join(format!("{base}.bak-{n}"));
        if !candidate.exists() {
            return candidate;
        }
        n += 1;
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::BTreeMap;

    /// A gzipped tarball holding `files`.
    fn archive(files: &[(&str, &str)]) -> Vec<u8> {
        let gz = flate2::write::GzEncoder::new(Vec::new(), flate2::Compression::fast());
        let mut tar = tar::Builder::new(gz);
        for (name, body) in files {
            let mut h = tar::Header::new_gnu();
            h.set_size(body.len() as u64);
            h.set_mode(0o644);
            h.set_cksum();
            tar.append_data(&mut h, name, body.as_bytes())
                .expect("append to an in-memory tarball");
        }
        tar.into_inner()
            .expect("finish the tarball")
            .finish()
            .expect("finish the gzip stream")
    }

    fn tree(dir: &Path) -> BTreeMap<String, String> {
        let mut out = BTreeMap::new();
        fn walk(root: &Path, at: &Path, out: &mut BTreeMap<String, String>) {
            for e in std::fs::read_dir(at).expect("read a directory of the tree") {
                let p = e.expect("entry").path();
                if p.is_dir() {
                    walk(root, &p, out);
                } else {
                    let rel = p
                        .strip_prefix(root)
                        .expect("under root")
                        .display()
                        .to_string();
                    out.insert(rel, std::fs::read_to_string(&p).expect("read a file"));
                }
            }
        }
        walk(dir, dir, &mut out);
        out
    }

    #[test]
    fn two_installers_taking_turns_leave_one_version_whole() {
        // The consumer's machine: two builds of smix, each with its own
        // sources, syncing one directory. Whatever the interleaving, the
        // directory must end as exactly one of them, stamp included.
        let a = archive(&[("common.txt", "A"), ("only_a.txt", "a")]);
        let b = archive(&[("common.txt", "B"), ("only_b.txt", "b")]);
        let root = tempfile::tempdir().expect("tempdir");
        let dst = root.path().join("android-runner");

        std::thread::scope(|scope| {
            for i in 0..8 {
                let (bytes, stamp) = if i % 2 == 0 { (&a, "A") } else { (&b, "B") };
                let dst = &dst;
                scope.spawn(move || {
                    for _ in 0..5 {
                        install_tree(dst, bytes, ".stamp", stamp, &[])
                            .expect("an install that loses a race still installs");
                    }
                });
            }
        });

        let got = tree(&dst);
        let want_a: BTreeMap<String, String> =
            [("common.txt", "A"), ("only_a.txt", "a"), (".stamp", "A\n")]
                .into_iter()
                .map(|(k, v)| (k.to_string(), v.to_string()))
                .collect();
        let want_b: BTreeMap<String, String> =
            [("common.txt", "B"), ("only_b.txt", "b"), (".stamp", "B\n")]
                .into_iter()
                .map(|(k, v)| (k.to_string(), v.to_string()))
                .collect();
        assert!(
            got == want_a || got == want_b,
            "the directory is not one version: {got:?}"
        );
        let staging: Vec<_> = std::fs::read_dir(root.path())
            .expect("read the parent")
            .map(|e| e.expect("entry").file_name().to_string_lossy().to_string())
            .filter(|n| n.contains(".staging-"))
            .collect();
        assert!(staging.is_empty(), "scratch left behind: {staging:?}");
    }
}
