[package]
name = "smix-contract-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[workspace]

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.smix-contract]
path = ".."

[profile.release]
debug = 1

[[bin]]
name = "contract_parse"
path = "fuzz_targets/contract_parse.rs"
test = false
doc = false
bench = false

[[bin]]
name = "reconcile_any"
path = "fuzz_targets/reconcile_any.rs"
test = false
doc = false
bench = false
