#!/usr/bin/env python3
"""Write the verb-by-form table into the guide, from the table itself.

The guide said "any selector position accepts `ocrText:`" directly
above a list of the four verbs that read it. A sentence and a list, in
the same paragraph, disagreeing — because both were written by hand
and neither was derived from anything.

So this asks the compiled table and writes the answer between markers.
`--check` compares instead of writing, which is what the gate runs: a
guide that has drifted from the code is a guide that will be believed.
"""

import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
GUIDE = os.path.join(ROOT, "docs", "ai-guide", "03-selectors.md")
BEGIN = "<!-- BEGIN selector-matrix (generated by scripts/dev/gen-selector-matrix.py) -->"
END = "<!-- END selector-matrix -->"

# How an author writes each slot, and the order they meet them.
SLOT_LABEL = [
    ("TapOnTarget", "`tapOn`"),
    ("DoubleTapTarget", "`doubleTapOn`"),
    ("LongPressTarget", "`longPressOn`"),
    ("RepeatTapTarget", "`repeatTap`"),
    ("FillTarget", "`inputText: { <target>, text }`"),
    ("CopyTextSource", "`copyTextFrom`"),
    ("AssertVisibleTarget", "`assertVisible`"),
    ("AssertNotVisibleTarget", "`assertNotVisible`"),
    ("WaitVisibleTarget", "`extendedWaitUntil.visible`"),
    ("WaitNotVisibleTarget", "`extendedWaitUntil.notVisible`"),
    ("ScrollTarget", "`scrollUntilVisible`"),
    ("RunFlowGate", "`runFlow.when.visible` / `.notVisible`"),
    ("AnnotationAnchor", "`takeScreenshot` annotation `at:`"),
]
FORMS = ["OcrText", "LocalizedText", "AnchorRelative"]
FORM_LABEL = {"OcrText": "`ocrText:`", "LocalizedText": "`localizedText:`",
              "AnchorRelative": "`anchored:`"}


def cells() -> dict:
    out = subprocess.run(
        ["cargo", "test", "-p", "smix-adapter-maestro", "--test",
         "every_cell_is_a_decision", "--", "--nocapture", "print_the_table"],
        cwd=ROOT, capture_output=True, text=True,
    ).stdout
    found = dict(
        ((m[0], m[1]), m[2])
        for m in re.findall(r"CELL (\S+):(\S+) (DISPATCHED|REFUSED)", out)
    )
    if not found:
        raise SystemExit(
            "gen-selector-matrix: the table printed nothing. Refusing to write an "
            "empty matrix — a guide that lists no verbs agrees with every claim."
        )
    return found


def render(found: dict) -> str:
    head = "| verb | " + " | ".join(FORM_LABEL[f] for f in FORMS) + " |"
    rule = "|---|" + "---|" * len(FORMS)
    rows = []
    for slot, label in SLOT_LABEL:
        marks = []
        for form in FORMS:
            verdict = found.get((slot, form))
            if verdict is None:
                raise SystemExit(f"gen-selector-matrix: no cell for {slot} × {form}")
            marks.append("reads it" if verdict == "DISPATCHED" else "refuses, and says why")
        rows.append(f"| {label} | " + " | ".join(marks) + " |")
    return "\n".join([head, rule, *rows])


def main() -> int:
    table = render(cells())
    src = open(GUIDE, encoding="utf-8").read()
    if BEGIN not in src or END not in src:
        print(
            f"gen-selector-matrix: {GUIDE} has no markers. The generated block has "
            f"to have somewhere to go.",
            file=sys.stderr,
        )
        return 1
    before, rest = src.split(BEGIN, 1)
    _, after = rest.split(END, 1)
    new = f"{before}{BEGIN}\n\n{table}\n\n{END}{after}"
    if "--check" in sys.argv:
        if new != src:
            print("gen-selector-matrix: the guide's matrix is not what the table says.")
            print("  Run scripts/dev/gen-selector-matrix.py and commit.")
            return 1
        print(f"gen-selector-matrix: clean — {len(SLOT_LABEL)} verbs, straight from the table")
        return 0
    open(GUIDE, "w", encoding="utf-8").write(new)
    print(f"gen-selector-matrix: wrote {len(SLOT_LABEL)} verbs into {GUIDE}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
