#!/usr/bin/env python3
"""Harness for generated-artifacts-are-load-bearing.py.

Each case builds a fixture tree and runs the scanner against it via
SMIX_GENARTIFACT_ROOT, asserting the fixture really has (or lacks) the
thing under test before checking the verdict — a red must be the scanner's
judgement, not a broken fixture. Covers empty-predicate both sides:
presence (non-empty discovery + required present) and coverage (each
artifact has a wired freshness gate).
"""
import os
import subprocess
import sys
import tempfile

SCANNER = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                       "generated-artifacts-are-load-bearing.py")


def write(root, rel, content):
    path = os.path.join(root, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(content)


def run(root, required=None):
    env = dict(os.environ, SMIX_GENARTIFACT_ROOT=root)
    if required is not None:
        env["SMIX_GENARTIFACT_REQUIRED"] = required
    return subprocess.run([sys.executable, SCANNER], env=env,
                          capture_output=True, text=True)


def fixture_clean(root):
    # a self-declared generated file, a gate that references it, and a
    # preflight that invokes the gate.
    write(root, "gen.txt", "// auto-generated by TESTGEN\nbody\n")
    write(root, "scripts/dev/gen-fresh.sh", "#!/usr/bin/env bash\n# regenerate gen.txt and diff\n")
    write(root, "scripts/dev/preflight.sh", "#!/usr/bin/env bash\nbash scripts/dev/gen-fresh.sh\n")
    write(root, "scripts/release/ship.sh", "#!/usr/bin/env bash\n: ship\n")


fails = []


def expect(cond, msg):
    if not cond:
        fails.append(msg)


# --- clean: everything present and wired -> exit 0 --------------------
with tempfile.TemporaryDirectory() as root:
    fixture_clean(root)
    expect(os.path.exists(os.path.join(root, "gen.txt")), "clean fixture missing gen.txt")
    r = run(root, required="gen.txt")
    expect(r.returncode == 0, f"clean: expected exit 0, got {r.returncode}: {r.stdout}{r.stderr}")

# --- M-cover: artifact present, no gate covering it -> red ------------
with tempfile.TemporaryDirectory() as root:
    fixture_clean(root)
    # remove the gate's reference to gen.txt (mutation: coverage gone)
    write(root, "scripts/dev/gen-fresh.sh", "#!/usr/bin/env bash\n# regenerate SOMETHING ELSE\n")
    body = open(os.path.join(root, "scripts/dev/gen-fresh.sh")).read()
    expect("gen.txt" not in body, "M-cover mutation did not land (gate still names gen.txt)")
    r = run(root, required="gen.txt")
    expect(r.returncode == 1, f"M-cover: expected exit 1, got {r.returncode}")
    expect("no freshness gate" in r.stdout, f"M-cover: wrong verdict: {r.stdout}")

# --- M-airA: no generated files at all -> reading air ----------------
with tempfile.TemporaryDirectory() as root:
    write(root, "scripts/dev/preflight.sh", "#!/usr/bin/env bash\n: nothing\n")
    write(root, "plain.txt", "just a normal file\n")
    # assert the fixture really has no self-declared generated file
    expect(not any("auto-generated" in open(os.path.join(root, f)).read()
                   for f in ["plain.txt"]), "M-airA fixture unexpectedly has a marker")
    r = run(root, required="")
    expect(r.returncode == 1, f"M-airA: expected exit 1, got {r.returncode}")
    expect("reading air" in r.stdout, f"M-airA: wrong verdict: {r.stdout}")

# --- M-airB: a required artifact is not discovered -> red ------------
with tempfile.TemporaryDirectory() as root:
    fixture_clean(root)
    expect(not os.path.exists(os.path.join(root, "missing.txt")),
           "M-airB fixture unexpectedly has missing.txt")
    r = run(root, required="missing.txt")
    expect(r.returncode == 1, f"M-airB: expected exit 1, got {r.returncode}")
    expect("required to be a discovered generated artifact" in r.stdout,
           f"M-airB: wrong verdict: {r.stdout}")

if fails:
    print("generated-artifacts-are-load-bearing.test: FAIL")
    for f in fails:
        print(f"  - {f}")
    sys.exit(1)
print("generated-artifacts-are-load-bearing.test: clean — 4 cases (clean + M-cover + M-airA + M-airB), each verdict is the scanner's own")
