#!/usr/bin/env python3
"""Every self-declared generated artifact must have a freshness gate.

A committed file that says "auto-generated" in its header is load-bearing
the moment code depends on it, and it drifts from its source between the
runs that regenerate it. Before 6.0.0, `swipeAtCoord` reached the Rust
bindings but not `crates/smix-node/index.d.ts`, and only a dry-run caught
it. The fix there was a freshness gate (`napi-dts-fresh.sh`); the fix
here is the *rule* — not a list of paths to babysit, but a scan that
discovers every self-declared generated file and asserts each one is
watched by a freshness gate wired into preflight or ship.

Discovery reads the first two lines of every tracked text file for an
`auto-generated` / `autogenerated` marker, and excludes `.xcframework/`
by bundle boundary (a build-output blob rebuilt whole, whose binding
symbols `ffi-bindings-fresh` already pins with `nm`).

By empty-predicate (.claude/rule/empty-predicate.md) the presence side is
explicit: the discovery set must be non-empty and must contain the known
load-bearing artifacts — a scan that discovers nothing (marker renamed,
files moved) certifies air, so it fails loudly instead.

Env overrides (used by the .test.py harness against fixture trees):
  SMIX_GENARTIFACT_ROOT      — scan this tree instead of the repo
  SMIX_GENARTIFACT_REQUIRED  — comma-separated required rel-paths
"""
import os
import re
import subprocess
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
SCAN_ROOT = os.environ.get("SMIX_GENARTIFACT_ROOT", ROOT)
IS_FIXTURE = os.path.abspath(SCAN_ROOT) != ROOT

MARKER = re.compile(r"auto-?generated", re.I)

# The load-bearing artifacts that must be discovered. In the real repo
# these are the three uniffi/napi outputs; a fixture overrides them.
DEFAULT_REQUIRED = {
    "crates/smix-node/index.d.ts",
    "swift-bridge/Sources/SmixCoreFFIBindings/Generated/smix.swift",
    "android-runner/sdk/src/main/kotlin/uniffi/smix/smix.kt",
}
_req_env = os.environ.get("SMIX_GENARTIFACT_REQUIRED")
if _req_env is not None:
    REQUIRED = {p for p in (x.strip() for x in _req_env.split(",")) if p}
elif IS_FIXTURE:
    REQUIRED = set()
else:
    REQUIRED = set(DEFAULT_REQUIRED)

# The two files a gate must be reachable from to count as "wired".
WIRING_FILES = ["scripts/dev/preflight.sh", "scripts/release/ship.sh"]
GATE_DIRS = ["scripts/dev", "scripts/release"]


def candidate_files():
    if IS_FIXTURE:
        out = []
        for dirpath, _dirs, files in os.walk(SCAN_ROOT):
            for f in files:
                out.append(os.path.relpath(os.path.join(dirpath, f), SCAN_ROOT))
        return out
    res = subprocess.run(
        ["git", "-C", SCAN_ROOT, "ls-files"],
        capture_output=True, text=True, check=True,
    )
    return [l for l in res.stdout.splitlines() if l]


def is_self_declared_generated(rel):
    if ".xcframework/" in rel:
        return False
    path = os.path.join(SCAN_ROOT, rel)
    try:
        with open(path, "r", encoding="utf-8", errors="ignore") as fh:
            head = [next(fh, ""), next(fh, "")]
    except (OSError, StopIteration):
        return False
    return any(MARKER.search(line) for line in head)


def read(path):
    try:
        with open(path, "r", encoding="utf-8", errors="ignore") as fh:
            return fh.read()
    except OSError:
        return ""


def wired_gate_texts():
    """Basenames of gate scripts invoked by preflight or ship, mapped to
    the gate's own body text."""
    wiring_text = "".join(read(os.path.join(SCAN_ROOT, w)) for w in WIRING_FILES)
    # The orchestrators themselves are not freshness gates — they invoke
    # gates. Excluding them stops a mere comment mention of an artifact in
    # preflight/ship from counting as coverage (it would have mapped
    # index.d.ts to preflight.sh, certifying a gate that isn't one).
    orchestrators = {os.path.basename(w) for w in WIRING_FILES}
    gates = {}
    for d in GATE_DIRS:
        dpath = os.path.join(SCAN_ROOT, d)
        if not os.path.isdir(dpath):
            continue
        for f in os.listdir(dpath):
            if not (f.endswith(".sh") or f.endswith(".py")):
                continue
            if f.endswith(".test.py") or f in orchestrators:
                continue
            if f in wiring_text:  # the gate is invoked by preflight/ship
                gates[f] = read(os.path.join(dpath, f))
    return gates


def covering_gate(rel, gates):
    """A wired gate covers an artifact if its body references the artifact
    by relative path or by basename."""
    base = os.path.basename(rel)
    for name, body in gates.items():
        if rel in body or base in body:
            return name
    return None


def main():
    problems = []
    discovered = {f for f in candidate_files() if is_self_declared_generated(f)}

    # presence side (empty-predicate): non-empty and contains the known.
    if not discovered:
        problems.append(
            "discovered no self-declared generated artifacts at all — the marker "
            "was renamed, the files moved, or discovery is reading air"
        )
    for req in sorted(REQUIRED - discovered):
        problems.append(
            f"{req} is required to be a discovered generated artifact and was not "
            f"found — its header marker or its path changed, and the scan would "
            f"pass without ever seeing it"
        )

    gates = wired_gate_texts()
    for rel in sorted(discovered):
        if not covering_gate(rel, gates):
            problems.append(
                f"{rel} is a self-declared generated artifact with no freshness "
                f"gate wired into preflight or ship — it will drift from its "
                f"source the way index.d.ts did before 6.0.0"
            )

    if problems:
        print("generated-artifacts-are-load-bearing: FAIL")
        for p in problems:
            print(f"  - {p}")
        return 1

    covered = ", ".join(
        f"{os.path.basename(r)}→{covering_gate(r, gates)}" for r in sorted(discovered)
    )
    print(
        f"generated-artifacts-are-load-bearing: clean — "
        f"{len(discovered)} generated artifact(s), each with a wired freshness "
        f"gate ({covered})"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
