[package]
name = "smix-screen-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[workspace]

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
serde_json = "1"

[dependencies.smix-screen]
path = ".."

[profile.release]
debug = 1

[[bin]]
name = "a11y_node_parse"
path = "fuzz_targets/a11y_node_parse.rs"
test = false
doc = false
bench = false
