/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class SmixNodeDriver {
  /**
   * Build a driver aimed at a runner on `port`. Construction connects to
   * nothing — it only builds the reqwest-backed client — so a never-served
   * port is fine until the first call. `port` is `u32` because napi has no
   * native `u16`; the client's port is `u16`, so the boundary narrows here.
   */
  constructor(port: number)
  /**
   * Tap the normalized point `(nx, ny)` (each 0..1) and return the hit
   * chain as JSON — the named elements containing the point, innermost
   * first, the same `TapAtCoordResult` the wire returns. JSON string
   * rather than a marshaled struct keeps C1's boundary minimal; the Node
   * side reads `.chain`. The Arc is cloned before the await so the future
   * owns its client and never borrows `&self` across napi's runtime.
   */
  tapAtCoord(nx: number, ny: number): Promise<string>
  /**
   * Swipe between two normalised points, the authorised coordinate
   * escape hatch for swipe (§9 #3). Two points rather than one: a
   * swipe is a path, and tap's single-point shape does not describe
   * one.
   */
  swipeAtCoord(fromX: number, fromY: number, toX: number, toY: number): Promise<void>
  /**
   * Tap the element with accessibility identifier `id`. Returns whether a
   * matching element was found and tapped — selectors resolve to an id in
   * the SDK layer, so no selector crosses the boundary (parity with the
   * UniFFI surface).
   */
  tapById(id: string): Promise<boolean>
  /** Type `text` into the focused element. */
  inputText(text: string): Promise<void>
  /**
   * Press a hardware/keyboard key by its camelCase wire name (e.g.
   * `return`, `arrowUp`). The keyboard diagnostic payload is dropped —
   * fire-and-return, matching the UniFFI surface.
   */
  pressKey(key: string): Promise<void>
  /** Swipe once in a camelCase direction (`up`/`down`/`left`/`right`). */
  swipe(direction: string): Promise<void>
  /**
   * Snapshot the accessibility tree as JSON — the full scope (`None`), the
   * same convention as the UniFFI surface. The Node side parses it.
   */
  snapshotTree(): Promise<string>
  /** The system popups currently on screen, as JSON. */
  systemPopups(): Promise<string>
  /**
   * Open a session bound to `bundle_id` and return a handle for the
   * lifecycle verbs. The session shares this driver's client (connection
   * pool). `activate: false` mirrors the UniFFI surface — the caller
   * foregrounds explicitly.
   */
  openSession(bundleId: string): Promise<SmixNodeSession>
}

/**
 * A handle to an open runner session. Only the lifecycle verbs need the
 * session id, so they live here; the stateless act/sense verbs stay on the
 * driver.
 */
export declare class SmixNodeSession {
  /** Launch (or relaunch fresh) the session's app. */
  launchApp(): Promise<void>
  /** Terminate the session's app. */
  terminateApp(): Promise<void>
  /** Terminate and relaunch the session's app in one cycle. */
  relaunchApp(): Promise<void>
}

/**
 * Resolve a selector against a tree and return the matched identifiers.
 * Index modifiers pick a single result; otherwise every match's id.
 */
export declare function resolveSelector(treeJson: string, selectorJson: string): Array<string>

/**
 * Count selector matches against a tree (ignores index modifiers, matching
 * Playwright "match all" semantics).
 */
export declare function resolveSelectorCount(treeJson: string, selectorJson: string): number

/**
 * Resolve a selector and return each match's accessibility label (empty
 * string where a match has none), aligned 1:1 with the match set.
 */
export declare function resolveSelectorLabels(treeJson: string, selectorJson: string): Array<string>
